# Site settings
baseurl = "http://odushyn.github.io/"
languageCode = "en-us"
title = "Some blog"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "odushyn"
# Solve problem with CSS loading
canonifyurls = true

[params]
	name = "Oleksandr Dushyn"
	description = "Blogging site"
	bio = "the one who tries to understand"
	# Enter optionally your twitter account
	twitter = "ODushyn"
	enableRSS = false

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	projects = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "The one who tries to understand"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://twitter.com/ODushyn"
    facebook = "https://www.facebook.com/oleks.dushyn"
    github   = "https://github.com/ODushyn"